name: we_chat

description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # For integrating firebase
  firebase_core: ^2.24.2

  # For handling google sign in
  firebase_auth: ^4.15.3

  # For accessing cloud firestore database
  cloud_firestore: ^4.13.6

  # For accessing firebase storage
  firebase_storage: ^11.5.6

  # For handling firebase authentication
  google_sign_in: ^6.2.1

  # For showing network images
  cached_network_image: ^3.3.0

  # For picking images
  image_picker: ^1.0.5

  # For showing emojis
  emoji_picker_flutter: ^2.1.1

  # For accessing firebase messaging (push notifications) for mobile
  firebase_messaging: ^14.7.9

  # For calling RestAPIs
  http: ^1.2.1

  # For creating notification channel for mobile
  flutter_notification_channel: ^3.1.0

  # For showing Toasts on mobile
  fluttertoast: ^8.2.4

  # For saving images to gallery on mobile
  gal: ^2.3.0
  dio: ^5.4.2+1

  # For date time formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

#   flutter_launcher_icons: "^0.13.1"

# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/icon.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "images/icon.png"
#   windows:
#     generate: true
#     image_path: "images/icon.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Google Font
      fonts:
        - asset: assets\fonts\NotoColorEmoji-Regular.ttf

    - family: seguiemj
      fonts:
        - asset: assets\fonts\NotoColorEmoji.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700